// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAFL_EiMQLv2kLZSn4q7Ef-j_5CsXmb-0',
    appId: '1:827975921714:web:3d2533e0ade627c1fc4c2b',
    messagingSenderId: '827975921714',
    projectId: 'ecommerceflutter-709c8',
    authDomain: 'ecommerceflutter-709c8.firebaseapp.com',
    storageBucket: 'ecommerceflutter-709c8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYfX3B9n72ZpIXUBuwQf0bMH4pUkZDgm0',
    appId: '1:827975921714:android:e1a6da01cf43cdacfc4c2b',
    messagingSenderId: '827975921714',
    projectId: 'ecommerceflutter-709c8',
    storageBucket: 'ecommerceflutter-709c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDx1FpuhDcyVHne-UmZAlstmHOPDgQifw',
    appId: '1:827975921714:ios:22f43fe54ff2a13dfc4c2b',
    messagingSenderId: '827975921714',
    projectId: 'ecommerceflutter-709c8',
    storageBucket: 'ecommerceflutter-709c8.firebasestorage.app',
    androidClientId: '827975921714-kjqatpeopcu9jp11162tlmjmr55mo90r.apps.googleusercontent.com',
    iosClientId: '827975921714-45of5rvrj1ntmhlgnnq4pa8bq2h6bvo5.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceFlutter',
  );

}